### ISSUE TITLE
autodetect CI

### ISSUE THREAD

**Issue by mgxd** [sensein/etelemetry-client#1]
something similar to https://github.com/watson/is-ci, in order to avoid excessive entries

**Comment by yarikoptic** [comment]
Fwiw it might still be useful to get those registered, just annotated properly.

**Comment by effigies** [comment]
I didn't find a Python package to do the equivalent, but I did a quick search for predefined environment variables for different CIs that should cover 99%+ of the cases:

```Python
CI_VARS = {
    'AppVeyor': ('APPVEYOR', 'CI'),
    'Azure': ('AGENT_OS', 'BUILD_BUILDID'),  # This one needs testing...
    'CircleCI': ('CIRCLECI', 'CI'),
    'Jenkins': ('EXECUTOR_NUMBER', 'BUILD_TAG'),
    'Travis': ('TRAVIS', 'CI'),
    'Unknown': 'CI',  # Fallback
    }
```

Did it as a dict in case you're interested in keeping track of which CIs are being used.

**Comment by mgxd** [comment]
thanks @effigies - I was looking into how the package in my op gathers it and it looks to be similar

* basic check for CI
https://github.com/watson/ci-info/blob/8d2b5bd5ebd11a3a7cc4ae7457aaf6c2188c5ca6/index.js#L52-L59
* vendor specific information / is PR?
https://github.com/watson/ci-info/blob/master/vendors.json

@yarikoptic we haven't properly stress tested the etelemetry suite yet, and few packages have been et'ed that logging these should be fine. But we'll have to come back to the question of whether having excessive logging affects performance once we have integrated more projects

**Comment by mgxd** [comment]
we can leverage [mgxd/ci-info](https://github.com/mgxd/ci-info) on requests
