### ISSUE TITLE
Automagically detect and disable "call home" when ran on CIs

### ISSUE THREAD

**Issue by yarikoptic** [sensein/etelemetry-client#17]
I guess current counts might counting also invocations on CIs unless developers **explicitly** disable ET by exporting `NO_ET=1` env var.  People will forget etc, so current counts might be artificially blown up.
Most of the CIs make themselves detectable by exposing environment variables specific to the CI.  I think etelemetry-client should check for most common (travis, circle ci, github workflows), issue a log message that no checking on CI, and do not report to server

**Comment by mgxd** [comment]
this was discussed in #1 

FWIW, we should be sending information to the server whenever the request comes from a detected CI, which should be then filterable down the line
https://github.com/sensein/etelemetry-client/blob/e7466188518e570e476fc0b72e96819f3d017af9/etelemetry/client.py#L16-L18

**Comment by yarikoptic** [comment]
d'oh -- right! sorry for the noise... forgot and was `git grep -i travis` ;) 

Now - someone needs to package it (ci-info) for conda-forge!
