### ISSUE TITLE
No module named 'ci_info'

### ISSUE THREAD

**Issue by liamtimms** [sensein/etelemetry-client#21]
Hi all, 

I'm trying to use the testing function `pytest -v --doctest-modules nipype` on my system for my nipype 1.5.0 build. I am receiving the error: 

```
______________ ERROR collecting interfaces/spm/tests/test_base.py ______________
/usr/lib/python3.8/site-packages/etelemetry/client.py:5: in <module>
    import ci_info
E   ModuleNotFoundError: No module named 'ci_info'

```
Is there a dependency I am missing? My google searches are drowned out in general information about CI + python and I haven't been able to identify a specific python module. 

System information: 

```
Python 3.8.3
python-etelemetry 0.2.1

```

Thank you!

**Comment by liamtimms** [comment]
never mind, just found https://pypi.org/project/ci-info/#description so I'll close this issue.

**Comment by mgxd** [comment]
FWIW, you'll have to run:

`pip install ci-info`

**Comment by liamtimms** [comment]
@mgxd cheers thanks, I was foolishly looking for `ci_info` and missing `ci-info` .
