### ISSUE TITLE
Status codes

### ISSUE THREAD

**Issue by effigies** [sensein/etelemetry-client#31]
While "I'm using this!" is a nice flag for libraries, one feature that would make this more useful for end-user tools would be to be able to have the following statuses:

* STARTED
* SUCCESS
* FAILURE

I would imagine the API roughly as:

```Python
import etelemetry

run_uuid = etelemetry.check_available_version("my/project", "1.0.0", status="START")

...

etelemetry.update_status(run_uuid, status="FAILURE" if exit_code else "SUCCESS")
sys.exit(exit_code)
```

WDYT?

**Comment by oesteban** [comment]
This would be very helpful.

Additional suggestions:

- Introduce a concept of user (to have a notion of "new" and "returning" users)
- Introduce a concept of session (have also some session_uuid that clients can set the way they consider useful). For instance, in the case of fMRIPrep I would consider "same-session" all the participants associated to the same input dataset by the same user.

I'm not sure of how rigorous these things can be done from a technical perspective (I know, e.g., on the web it took some time until browsers provided standard UserAgent information) and that tracking sessions heavily relied on cookies...

**Comment by effigies** [comment]
I think the solution is migas, not continuing to develop ET.

**Comment by yarikoptic** [comment]
oh, nice, didn't know that an alternative was born... by the same ppl... odd.
Convenience link: https://github.com/nipreps/migas-server https://github.com/nipreps/migas-py
