### ISSUE TITLE
Network sandboxed tests

### ISSUE THREAD

**Issue by TheChymera** [sensein/etelemetry-client#41]
I am obviously aware that the package's usage is internet-focused, nevertheless, would it be possible to have more tests providing hopefully a more accurate predictor for the package's ability to function which work inside a network sandbox?

As of `0.3.0` the package has 4 tests, and 3 of them fail with `urllib` or socket errrors: https://ppb.chymera.eu/e46a99.log

**Comment by mgxd** [comment]
How about we just mark them to be skipped if no internet connection is available?

**Comment by TheChymera** [comment]
@mgxd sure, that would help avoid manual skipping, so it's in any case a plus. But more sandboxable tests would also be cool in as far as you're interested or this is at all feasible.
